### ISSUE TITLE
Disallow usage of specific KW

### ISSUE THREAD

**Issue by juszynsk** [MarketSquare/robotframework-robocop#1067]
Hi, Could You add rule where we can specify a Keyword which should not be used in RF code ?

**Comment by bhirsz** [comment]
Yes, it can be implemented as community rule. It would reuse most of the code from the ``sleep-keyword-used`` with the possiblity to configure keyword name and optionally library/resource name (if used as library.keyword)

**Comment by bhirsz** [comment]
I need to think how to handle multiple keywords - most likely allow to define multiple keywords (ie rule-name:keywords:keyword1,keyword2) .

**Comment by bhirsz** [comment]
I have implemented rule in the linked PR. Can you @juszynsk check the PR tests and see if it will cover your needs?

**Comment by juszynsk** [comment]
Hi @bhirsz looks fine for me :)
