### ISSUE TITLE
[Bug] --ext-rules path in argument file should be relative to the argument file location

### ISSUE THREAD

**Issue by rikerfi** [MarketSquare/robotframework-robocop#1071]
### What happened?

Running robocop with `--ext-rules` parameter takes a path relative to the location where the robocop is launched. When using the argument file with `-A` parameter then `--ext-rules` should be relative to the argument file. 

### What command/code did you try to run?

robocop tests/ -A tests/roboargs.txt

Argument file has following line:
--ext-rules libraries/robocop/

External rules are located to /tests/libraries/robocop

### What is the full error message?

Error: Fatal error: Failed to load external rules from file "/libraries/robocop/". Verify if the file exists

### What did you expect to happen instead?

Get ext-rules from the relative location to the argument file location.

For example in argument file:
`--ext-rules libraries/robocop/` could point relative to the argument file and `--ext-rules ./libraries/robocop/` could point relative to location robocop is launched.

### Operating System

Linux

### Robocop version

5.0.4

**Comment by bhirsz** [comment]
I'm quite sure I have implemented something similiar in Robocop (after Robotidy, which uses completely different config implementation). I need to check if I simply missed --ext-rules option or there is new bug introduced.

**Comment by bhirsz** [comment]
The first mention: https://github.com/MarketSquare/robotframework-robocop/blob/28e028e026ed3e1d94e7b8f20b7179581029f180/docs/releasenotes/2.8.0.rst#relative-paths-in-the-argument-files-693

I will mark it as a bug since it's supposed to work like that

**Comment by bhirsz** [comment]
I have checked and we indeed resolve relative paths for some options in the configuration files but for some reason I used 'config directory' as base for toml files and project root fro arg files. It looks like bug, I will fix it
