### ISSUE TITLE
[Bug] 0919 unused-argument warning emitted for argument used as start index of FOR ... IN ENUMERATE loop

### ISSUE THREAD

**Issue by Mercury37** [MarketSquare/robotframework-robocop#1073]
### What happened?

Minimal example:
```
*** Keywords ***
Example
    [Arguments]    ${start}    @{list}
    FOR    ${index}    ${value}    IN ENUMERATE    @{list}    start=${start}
        Log Many    ${index}    ${value}
    END
```

### What command/code did you try to run?

robocop tmp.resource

### What is the full error message?

```
D:\tmp.resource:1:1 [W] 0204 Missing documentation in resource file (missing-doc-resource-file)
D:\tmp.resource:2:1 [W] 0201 Missing documentation in 'Example' keyword (missing-doc-keyword)
D:\tmp.resource:3:20 [W] 0919 Keyword argument '${start}' is not used (unused-argument)
```

### What did you expect to happen instead?

unused-argument warning should not appear.

### Operating System

Windows 10

### Robocop version

5.0.4

**Comment by gohierf** [comment]
I have a similar issue with Except blocks, on 5.4.0

![image](https://github.com/user-attachments/assets/71283f7f-4056-4a01-b226-d8890ca2d608)
