### ISSUE TITLE
[Rule] No embedded keyword arguments

### ISSUE THREAD

**Issue by Lakitna** [MarketSquare/robotframework-robocop#1118]
Robot keywords allow you to set arguments in 2 ways: Through the `[Arguments]` tag and through embedded arguments. For details on embedded arguments see https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#embedding-arguments-into-keyword-name.

I would like a rule that disallows this pattern. It can result in hard to understand code. This rule could be called something like `no-embedded-keyword-arguments`.

I'm willing to write this rule. Let me know if you're interested in adding it.

**Comment by bhirsz** [comment]
It is valid rule, though obviously only for some people. Feel free to implement it but it would go as community rule (not enabled by default)

**Comment by Lakitna** [comment]
Yeah not everybody would like this one. I'll add this one to the community rules soon™️
