### ISSUE TITLE
Rule: Detect lowercased global variable

### ISSUE THREAD

**Issue by mnojek** [MarketSquare/robotframework-robocop#119]
According to RF User Guide it is recommended to keep global variables capitalized, as well as suite and test variables. Only local variables should stay lowercased.

**Comment by yo-ga** [comment]
Hi @mnojek, I'd like to implement this rule.
Would you be able to define the rule number, the severity, and the message?

**Comment by mnojek** [comment]
Hi @yo-ga. Just pick any next available id from naming checkers (03xx) - I think it's 14 (0314).
The severity should be WARNING and the message it's up to you. I will comment on your proposition if I will feel that something different could fit better. Get inspired by other rules from the same checker. Good luck 😉

**Comment by yo-ga** [comment]
After checking `VariableNamingChecker`, it has already covered capital letter cases.
Target PR: #268

**Comment by mnojek** [comment]
You're right @yo-ga . I'm closing this issue. Thanks for the notice!
