### ISSUE TITLE
Allow to choose what rule types are displayed when called --list option

### ISSUE THREAD

**Issue by mnojek** [MarketSquare/robotframework-robocop#149]
If the number of rules are big, the output of listing all of them becomes more and more difficult to read. If someone wants to just see all of the rules from one family, the program should support it. That's why I suggest adding pattern support as an argument for `--list` option, e.g. `robocop -l 10*` should list all spacing rules. It can be extended to support severities etc. To be discussed.

**Comment by bhirsz** [comment]
Completed with #213
