### ISSUE TITLE
Support BDD tests

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#159]

**Comment by mnojek** [comment]
You mean Gherkin?

**Comment by bhirsz** [comment]
Yes, Gherkin style. It's probably supported by us already but we need to add some tests for extra verification, or add some rules if needed.

**Comment by bhirsz** [comment]
The bdd support in Robot Framework works so you can add Given/Then/When/And words before keyword name and it will matched. Both calls are equivalent:
```
Given My Keyword
My Keyword
```
From this point Robocop dont need anything extra to support BDD. But it could be possible to add rule for checking if someone used one of BDD keywords without name of keyword:
```
Given
Given   More Than One Space
```
Initially I was opting against it (someone could define Given keyword for some purpose). But recently there was question about it on slack when someone didnt know he was supposed to prefix keyword name with BDD keyword and he separated it with two spaces. I will create new rule for such situations.
