### ISSUE TITLE
List possible configurations if provided wrong param name

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#201]
Example:
```
robocop --configure line-too-long:length_line:120
```
```
Provided param 'length_line' for rule 'line-too-long' does not exist. Available configurable for this rule:
severity
line_length
```

**Comment by mnojek** [comment]
I was thinking about the same today! It would be great to have such list of available configurables on demand without making a mistake in param configuration.

**Comment by bhirsz** [comment]
What about:

```
robocop --configure line-too-long:list_configurables
```
Or something like that to display available configurables without need to make typo ;)

**Comment by mnojek** [comment]
And what if you want to list them all?

**Comment by bhirsz** [comment]
For given rule, yes. We could also think about enhancing --list to also report on available configurables, but that would be separate issue

**Comment by mnojek** [comment]
I still don't feel like saying `robocop` to configure something and then as a value you ask him to just `list_configurables` is user-friendly. It would be very useful to have some kind of cli option to list all configurables for all rules and maybe it could also support glob patterns so you can e.g. list only documentation configurables: `--list-configurables *doc*` 
Just a loose idea.

**Comment by bhirsz** [comment]
I was also thinking about "--list-configurables" option but I opted against it due to too long output (hard to read). But with support for glob patterns I believe it will be nice addition. I will create separate issue for it since this issue is about listing available configurables only if there was typo in configuration.
