### ISSUE TITLE
Rule [W0302] work incorrect when type filename prefix before keyword name

### ISSUE THREAD

**Issue by Tanapat-S** [MarketSquare/robotframework-robocop#214]
I found that when i tried to run robocop with rule[W0302] on this script with command
`robocop -i W0302 robocop_checking.robot`
https://gist.github.com/Tanapat-S/7af3dcdfdb6a484c958ce0a12fdfb65e

it give me 1 warning
`robocop_checking.robot:3:0 [W] 0302 Keyword name should be capitalized`

Expecting this one should not give any error, isn't it ?

**Comment by bhirsz** [comment]
Yes, it should ignore libraries import. Of course it's more difficult as it could be library import or just part of the name ie This Is.Keyword. But we need way to detect that or at least ignore everything before '.' as workaround for time being. 

And thanks for catching this bug!
