### ISSUE TITLE
Restructure Checkers page in the documentation

### ISSUE THREAD

**Issue by szabolcstoth** [MarketSquare/robotframework-robocop#217]
The `Checkers` page currently contains the main groups and inside these groups the rules are grouped by the checker classes. Due to this behavior the rules are not always ordered by their IDs. Example: the `Spacing` group starts with rule `W1006`.

The current order inside `Spaces`:
`InconsistentUseOfTabsAndSpacesChecker`: `W1006`
`InvalidSpacingChecker`: `W1001`, `W1002`
`MissingTrailingBlankLineChecker`: `W1003`, `W1004`, `W1005`

It is obvious that we should put `InconsistentUseOfTabsAndSpacesChecker` class at the end since it has the `W1006`.

But what about the following scenario: we add a new rule to `InvalidSpacingChecker` with `W1007` (since we don't want to change the other rules' IDs due to incompatibility issues), how should we order the classes? The only possible solution I can see in this scenario is that we somehow restructure the `Checkers` page.

Example:
- The page still should have the main groups: `Comments`, `Tags`, etc.
- Inside the groups we can have the rules ordered by the IDs (no need to group/separate by the checker classes).
- And we can mention that which checker class contains the given rule (like we mention what parameters does it have).

**Comment by bhirsz** [comment]
I agree with you. We need to draft how the new documentation will look like and update our [templates](https://github.com/MarketSquare/robotframework-robocop/blob/master/docs/checkers.rst) and [data feeder](https://github.com/MarketSquare/robotframework-robocop/blob/ecc2ffc20db7ef7a595f2b1c743d03a99782d2cf/docs/conf.py#L82) . We use rst and sphinx for documentation generating [sphinx rtd scheme](https://sphinx-rtd-theme.readthedocs.io/en/stable/). This could serve as basic reference how it could like.

**Comment by bhirsz** [comment]
Current [checkers](https://robocop.readthedocs.io/en/latest/checkers.html) documentation is also taking a lot of space in the screen per rule. Maybe we could list rules in some kind of table? [ref](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/tables.html) But in that case I don't know how we could include configurable params into it

Rule-id  Rule-name

And we can rename checkers -> rules

**Comment by bhirsz** [comment]
I refactored our checker docs a bit, you can view test version here: https://robocop.readthedocs.io/en/refactor_docs/checkers.html 

What do you think & want we can improve further? @szabolcstoth @mnojek

**Comment by szabolcstoth** [comment]
Yes, this solves the original ordering issue inside the checkers, thanks for the fix!
Later on we can have a brainstorming session about how to improve the page further. 👍

**Comment by mnojek** [comment]
It works very good, @bhirsz ! I accepted the PR and it can be merged now.
