### ISSUE TITLE
8 Keywords per test case - need to distinguish "arrange" steps from "assert" steps

### ISSUE THREAD

**Issue by eldaduzman** [MarketSquare/robotframework-robocop#219]
**Is your feature request related to a problem? Please describe.**
It makes sense that "arrange" and "act" parts of the test will be limited, but assertions shouldn't be limited (or at least not the same extent).

**Describe the solution you'd like**
I think it would be neat if robocop could tell the difference between assertions (eg - page should contain or the new assertion syntax of browser library) and actual test operations (click button, type text, send request etc) and apply a different rule for them.

**Describe alternatives you've considered**
One alternative is to simply increase the number of keywords per test case.

**Additional context**

**Comment by bhirsz** [comment]
The number 8 was picked quite randomly. Although it does feel 'good' if the test case/keyword have mostly "act" parts (like you describe it). Do you have any idea how Robocop could distinguish between assertions and test operations? Unless keyword use specific tag - which actually would be good if everyone would follow this ie type:assert - we need different method. For example configurable list of ignore regex patterns:

--configure too-many-calls-in-test-case:ignore:"Should\s+"

**Comment by eldaduzman** [comment]
Yes I understand that 8 is an arbitrary magic number.
I like wise agree that overall the size of the test should be constrained.

In the browser library for example the keywords are tagged as assertions (or 'wait'):

`   @keyword(tags=["Wait", "PageContent"])
    def wait_for_elements_state(
        self,
        selector: str,
        state: ElementState = ElementState.visible,
        timeout: str = "",
    ):`

So maybe this could be one hook.
I understand that it's not a very easy feature to develop, because it could have different contexts in different libraries.

**Comment by bhirsz** [comment]
After some deliberation we decided to not implement this. It would be too difficult to implement (the context of what is assert keyword changes between libraries and can be changed between library version). And it would be aggainst the purpose of Robocop - which is simply RF static code analyzer. If the proposed limits are too low it can be configured or whole rule excluded altogether.
