### ISSUE TITLE
Plugin for IntelliJ IDEA

### ISSUE THREAD

**Issue by ShemTovYosef** [MarketSquare/robotframework-robocop#221]
Hi, will be excellent to have a plugin for IntelliJ IDEA that will show issues in editor itself

**Comment by bhirsz** [comment]
Do you mean somehow like Python issues in Pycharm? Some of the syntax errors are detected in real time for Python. We plan something similiar - to integrate with one of the existing Robot Framework plugins for intellij.

For now you can define Robocop as external tool in Pycharm/intellij and assign shortcut for it. I have it configured with macros (like pass currently open file as argument to Robocop) if press shortcuts it will run tests on file open in the screen. I can share screenshots of configuration if you want

**Comment by hinews** [comment]
Hi @bhirsz 
Yes, with syntax highlighting. Could you share the screenshots, thank you!

**Comment by bhirsz** [comment]
Go to File -> Settings -> Tools -> External Tools. Click + button to add new tool. Fill it out:

![image](https://user-images.githubusercontent.com/8532066/98238410-a2991a00-1f66-11eb-9ede-22f42c4ccfd9.png)

You can also add your own arguments (like excluding/including rules, configuring). 
Advanced option and output filters are required to get clickable links in issues list. 

After saving and closing settings window you can go back to settings and add new shortcut under Keymap -> External Tools


This is of course "poor man's integration with Intellij" but better than nothing ;). I'm already working on integrating with plugins that have syntax highlighting.

**Comment by bhirsz** [comment]
On side note external tools are really handy with small automation tasks in Pycharm/Intellij - I often have some python scripts that autoformat files for me or do different tasks. This is example of such tool https://github.com/bhirsz/robotframework-clean - but I did not have time to add better documentation for it. I usually have shortcut for things like 'split currently selected keyword in multilines' or 'align selected lines in column like view' to make working with RF code easier.

**Comment by hinews** [comment]
Hi @bhirsz 

Thank you for the detailed instruction, I tried it and the second plugin, these tools are great and it will be really cool to have them integrated into IntelliJ IDEA.

With regards,
Yosef

**Comment by hinews** [comment]
Only one question, is there any objectives to be compatible with robot 3.0.2?

**Comment by bhirsz** [comment]
Robocop needs 3.2.1 because it is introducing new robot api - with new parsing api which we're using when analysing Robot Framework code. But you can use Robocop to analyse code code written to be compatible with previous versions (although there could be some problems).

I will keep issue open until we get better integration with Intellij IDEA

**Comment by fabioz** [comment]
As a note, Robocop is being integrated with the Robot Framework Language Server (i.e.: https://github.com/robocorp/robotframework-lsp/issues/271), which has an integration with Intellij (https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server), so, keep an eye on it (it should be integrated in the next release: 0.11.0).

**Comment by bhirsz** [comment]
Closing this issue because Robocop is already integrated to LSP through https://github.com/robocorp/robotframework-lsp and should be available in PyCharm and Visual Studio Code. Note that it's best to install most recent version of Robocop globally (and update it frequently) because LSP is shipped with old version of Robocop that don't have recent fixes.
