### ISSUE TITLE
Documentation is always 0.0.1 version

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#228]
We're missing autoversioning in our documentation

**Comment by bhirsz** [comment]
Here it says 'latest' https://robocop.readthedocs.io/en/latest/index.html but:

1) If you go deeper it will be 0.0.1
2) You can't go back to previous version in docs

**Comment by MaciejWiczk** [comment]
@bhirsz I believe You need to tag it using GIT

**Comment by bhirsz** [comment]
> @bhirsz I believe You need to tag it using GIT

Youre right, but I also forgot to remove hardcoded '0.0.1' in conf.py for my docs generator ;) If I will do any of two (either remove hardcoded or switch to git tags) the issue will be fixed
