### ISSUE TITLE
Default config file 

### ISSUE THREAD

**Issue by BegovicAmar** [MarketSquare/robotframework-robocop#253]
**Is your feature request related to a problem? Please describe.**
There is no simple and unified way for a team to run the same set of linter rules (other than copy/pasting a long list of exclusions) 

**Describe the solution you'd like**
Introduce a default config file that will allow a team to configure their linter (this will allow team members to run a simple command and be unified with the rest of the team) 

**Describe alternatives you've considered**
none, sorry 

**Additional context**
![image](https://user-images.githubusercontent.com/48672093/108998965-f197c600-76a1-11eb-83e6-48a99ea237e3.png)

**Comment by bhirsz** [comment]
Like we discussed in slack we definitely need to support this. For now I'm going with:

 - default config filename should be '.filename', located in top directory (robocop will check current directory, and if not found it will go to parent directory until .git is found or top os dir)
 - syntax should be identical to --argumetfile (and cli)

I will try to take a look into it soon
