### ISSUE TITLE
Check for unused keywords

### ISSUE THREAD

**Issue by mcguier** [MarketSquare/robotframework-robocop#280]
That would be nice to have a feature when robocop could search for unused keywords.

**Comment by bhirsz** [comment]
This feature goes beyoned what static analyser are designed to - especially when Robot Framework can use dynamic keywords (ie. from variables) making it hard to check for unused keywords. I recommend using https://github.com/pbylicki/rfhub2 together with loading your results - it will display information how many times you used particular keyword.
