### ISSUE TITLE
Revise line and col information in all rules

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#289]
Most of our rules report only in first cell (col = 0) even if the problem occurs in the middle of line. Some of the rules also report im the wrong line.

We need to go through all rules and check how they report col and line information and fix if necessary.

**Comment by bhirsz** [comment]
@mnojek What should be start pos of line and col? Currently first line = 1, first col = 0. This cause some problems, for example PyCharm counts first line as 1 (and issues from external tools are 'shifted' by 1).

But most issues are looking ok in LSP (with some exceptions - to be fixed). If we change first col to 1 we would need to update most issues +1 and then decrease col by 1 when converting issues to lsp diagnostic since Range is 0 based: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#range

**Comment by mnojek** [comment]
Honestly, I have no idea what is the best option. I would just look at the other linters and see what approach do they have, e.g. pylint and others.

**Comment by bhirsz** [comment]
Unfortunately it's differs.. pylint starts from 0, pycodestyle from 1, flake8 from 1. IDEs typically support from 1. LSP plugin hovewer expect it from 0. 1's is bit more favoured though we would need to release our own Jenkins parser for Warnings plugin since we could not longer use Pylint one.
