### ISSUE TITLE
Misaligned variable cause fatal exception

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#292]
This code breaks robocop:
```
*** Variables ***
  ${var}  1
```

**Comment by mnojek** [comment]
Why? 😄

**Comment by bhirsz** [comment]
I was suprised too :D I was trying some stuff for (upcoming) AlignVariablesSection transformer for robotidy and then I noticed that we don't cover it anywhere in Robocop. I've tried and turns out ``EqualSignChecker`` is throwing fatal exception. I think it only happens in RF4 but I would need to double check.
