### ISSUE TITLE
[Rule] Equal signs convention should be configurable

### ISSUE THREAD

**Issue by mnojek** [MarketSquare/robotframework-robocop#295]
I see some people use equal signs `=` in variable assignment, both in Variables section or in local assignments. 
I think we should consider adding a rule that can detect inconsistent use of equal signs. Right now we only detect if the equal sign appears and then report it as a redundant but not all RF users perceive them useless. Some like to use equal signs for readability.
There are two ways equal signs can be written - with `" ="` our without `"="` preceding whitespace. If we detect such inconsistency, we should report it. 
Also some people use them only in local variables assignments, some use them only in variables section and some use them in both places. We need to think if we want to separate such cases for different rules or we want to treat them globally. For people who only use them in one of these places, we would need to ignore other places or force them to use it everywhere. Hard decision how to handle that.
We can also create one configurable rule where users can decide whether they want to use them with preceding whitespace, without whitespace, without equal sign at all or maybe just ignore it and do not report any issues about that.

**Comment by pekkaklarck** [comment]
Yes, there are various ways to use `=` in assignments with different people/teams having different preferences. You can omit it altogether, use it like `${x}=` or with a space like `${x} =`. Many also use different style with assistant within tests/keywords (using `=` w/ or w/o space seems most common) and in the variables section (omitting `=` seems most common). I don't think there's a single style that enough many agree that we should try to force everyone to follow. Except that whatever style is used, should be used consistently.

In my opinion it would be best if the linter would by default just check that you use the equal sign consistently and allow using any of the three alternatives. It should also allow using a different style in the variables section and elsewhere. You should then be allowed to set hard rules if needed.
