### ISSUE TITLE
Can't run single tests for rules

### ISSUE THREAD

**Issue by d-biehl** [MarketSquare/robotframework-robocop#320]
if I want to test for a single rule with:

    pytest -k test_rule[missing-whitespace-after-setting]

I get:

    ========================================================================== test session starts ==========================================================================
    platform win32 -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
    rootdir: C:\develop\robot\robotframework-robocop
    collected 220 items / 219 deselected / 1 selected
    
    tests\atest\test_rule.py E                                                                                                                                         [100%]
    
    ================================================================================ ERRORS ================================================================================= 
    _____________________________________________________ ERROR at setup of test_rule[missing-whitespace-after-setting] _____________________________________________________ 
    
        @pytest.fixture
        def robocop_instance():
    >       return Robocop(from_cli=True)
    
    tests\atest\conftest.py:8:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    robocop\run.py:48: in __init__
        self.config.parse_opts(from_cli=from_cli)
    robocop\config.py:260: in parse_opts
        args = self.parser.parse_args(args)
    C:\Program Files\Python39\lib\argparse.py:1821: in parse_args
        self.error(msg % ' '.join(argv))
    robocop\config.py:95: in error
        super().error(message)
    C:\Program Files\Python39\lib\argparse.py:2575: in error
        self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    self = CustomArgParser(prog='robocop', usage=None, description='Static code analysis tool for Robot Framework', formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=False)
    status = 2, message = 'robocop: error: unrecognized arguments: -k\n'
    
        def exit(self, status=0, message=None):
            if message:
                self._print_message(message, _sys.stderr)
    >       _sys.exit(status)
    E       SystemExit: 2
    
    C:\Program Files\Python39\lib\argparse.py:2562: SystemExit
    ------------------------------------------------------------------------- Captured stderr setup ------------------------------------------------------------------------- 
    usage: robocop [-i RULES] [-e RULES] [-rules EXT_RULES] [--no-recursive]
                   [-r REPORTS] [-f FORMAT] [-c CONFIGURABLE] [-l [PATTERN]]
                   [--list-configurables [PATTERN]] [--list-reports] [-o PATH]
                   [--filetypes FILETYPES] [-t THRESHOLD] [-A PATH]
                   [--ignore PATH] [-h] [-v]
                   [paths ...]
    robocop: error: unrecognized arguments: -k
    ======================================================================== short test summary info ======================================================================== 
    ERROR tests/atest/test_rule.py::test_rule[missing-whitespace-after-setting] - SystemExit: 2
    =================================================================== 219 deselected, 1 error in 0.57s ====================================================================

**Comment by bhirsz** [comment]
I think it's bug introduced with recent addition of Robocop API - we're stating that we're using cli (Robocop(from_cli=True)) and that's why Robocop is consuming whole sys.argv - together with pytest -k command. I will see how I can fix it - thanks for reporting it. 

I usually just run all the tests but I see that's not the ideal solution - I've started some refactoring in #317 to allow a bit more flexible tests as well.

**Comment by bhirsz** [comment]
I've fixed the bug and I have additionaly added new way of running just single test (since -k would not work anyway after recent refactors):

```
pytest --rule rule_name tests\atest
```

**Comment by mnojek** [comment]
@bhirsz  Have you added this to the documentation?
