### ISSUE TITLE
Show available values for configurable rule parameters

### ISSUE THREAD

**Issue by mnojek** [MarketSquare/robotframework-robocop#338]
The only way to get information what values are accepted for a configurable now it to provide incorrect value and get an exception with such information.
I would like to have available values listed when calling `-lc / --list-configurables` option and also have a default value marked.

**Comment by bhirsz** [comment]
Listing default value is possible (linked PR) but listing possible values is harder - and is only needed in two rules (inconsistent-assignment and inconsistent-assignment-in-variables). Do you agree to just showing default values for now or we want to code it somehow (ie giving meta var variable like it's done in pylint)?

**Comment by bhirsz** [comment]
It could work that way:
```
("line_length", "max_line_length", int, 'metavar, ie <int> or 'One of ... free description')
```

**Comment by mnojek** [comment]
I like the idea of optional description for a configurable.

**Comment by bhirsz** [comment]
I've updated linked PR so it's possible to use optional meta var to describe configurable.
