### ISSUE TITLE
Unify spelling of "test case" in names of rules.

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-robocop#357]
Mentions of test cases in names of default rules are written with hyphen (e.g. "too-long-test-case") or without it ("missing-doc-testcase"). This is confusing, especially when Robocop does not warn about unknown names of rules. Please, unify the spelling of the phrase.

**Comment by bhirsz** [comment]
Additionally from fixing the naming, "especially when Robocop does not warn about unknown names of rules" - do you want Robocop to print out the warning? It should fail when trying to configure not existing rule. But like you said it will ignore `robocop --include idontexist`. We could either print simple warning at the start of the run or throw exception (probably better).

**Comment by MoreFamed** [comment]
Yes, I wish Robocop to warn about unknown names of rules. I will open another issue regarding this, so the topic of this issue could remain just unification of spelling. Thanks.
