### ISSUE TITLE
[Rule] Identify consecutive whitelines

### ISSUE THREAD

**Issue by kvo-harmoney** [MarketSquare/robotframework-robocop#365]
Would be great to have a rule which can verify that there are no consecutive whitelines in place in your robot/resource file.

**Comment by bhirsz** [comment]
Do you mean this:

```
*** Keywords ***
Keyword
    Keyword1
    
     # second empty line in a row
     Keyword1
```

**Comment by kvo-harmoney** [comment]
That is indeed the proposal.
Ideally applicable on the entire file, so not limited to a particular section (keywords / test cases / ... )

**Comment by kvo-harmoney** [comment]
Awesome, thx.
