### ISSUE TITLE
Invalid number of empty lines in other section order

### ISSUE THREAD

**Issue by j3n5h** [MarketSquare/robotframework-robocop#382]
**Describe the bug**
If I disable the warning 0809 (section-out-of-order) the warning 1003 empty-lines-between-sections appears. I only can solve this when I change the order. In legacy code I want to accept another order. This message is confusing other members

**Expected behavior**
The warning 1003 should not appear if I have the right count of empty lines

**Screenshots**
![grafik](https://user-images.githubusercontent.com/73178992/124113158-670a0d80-da6b-11eb-8ba0-0fb5975d52ab.png)

**Version information**
Python 3.8
Robocop 1.7.1
Ubuntu 18.04

**Comment by mnojek** [comment]
Thanks for this bug report, @j3n5h. I will try to solve it soon.

**Comment by bhirsz** [comment]
It's also worth considering adding option for custom order of sections (so it for example check if Keywords are before Test Cases). It's done that way in Robotidy transformer MergeAndOrderSections.
