### ISSUE TITLE
import external rules through python package

### ISSUE THREAD

**Issue by fdaguin** [MarketSquare/robotframework-robocop#404]
**Is your feature request related to a problem? Please describe.**
Managing external rules is tedious when the latter need to be shared across multiple projects.

**Describe the solution you'd like**
At least, I'd like to vendor my external rules as Python packages. I'd like to specify a package name instead of a path to files/directory to load external rules.

At best, I'd like Robocop to provides a plugin system similar to [flake8](https://github.com/PyCQA/flake8).

**Comment by bhirsz** [comment]
Very good idea, I will see what we can do - it looks possible to be implemented.

**Comment by bhirsz** [comment]
Will this be enough::
```
robocop --ext-rules RobocopRules .
```
where RobocopRules are for example:
```
RobocopRules/
RobocopRules/__init__.py
RobocopRules/some_rules.py
setup.py
```
inside __init__.py:
```
from .some_rules import MissingKeywordName

all = ['MissingKeywordName']
```
inside some_rules.py:
```
from robocop.checkers import VisitorChecker
from robocop.rules import RuleSeverity


class MissingKeywordName(VisitorChecker):
    """ Checker for missing keyword name. """
    rules = {
        "9903": (
            "external-rule",
            "This is external rule",
            RuleSeverity.INFO
        )
    }

    def visit_KeywordCall(self, node):  # noqa
        if node.keyword and 'Dummy' not in node.keyword:
            self.report("external-rule", node=node)

```

Or you need more sofisticated methods of importing, ie dotted import?:
```
robocop --ext-rules mymodule.nested
```

I've implemented first example and it should be part of next release. I could improve it by adding other methods of importing (such as mentioned dotted import) but I'm not sure if it would be ready for next release.

**Comment by fdaguin** [comment]
Thanks a lot for your work @bhirsz, the dotted import is exactly what I needed !
