### ISSUE TITLE
Create Robocop github action

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#414]
Create separate Robocop github actions so others can easily define workflow with our tool, ie:
```
- name: Robocop lint
  uses: MarketSquare/actions-robocop@master
```

First version should only support configuraton from file. For github annotations we will need ProblemMatcher file like:
https://github.com/ammaraskar/gcc-problem-matcher/blob/master/gcc_matcher.json
https://github.com/korelstar/xmllint-problem-matcher/blob/master/xmllint-matcher.json
https://github.com/codespell-project/actions-codespell/blob/master/codespell-problem-matcher/codespell-matcher.json

It would be best if Robocop could generate ProblemMatcher file when run with special option (because this file will change depending on configured format).

**Comment by bhirsz** [comment]
Action repo: https://github.com/MarketSquare/actions-robocop

**Comment by bhirsz** [comment]
Because of "MarketSquare must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it." I will move action repo to my personal repository.

**Comment by bhirsz** [comment]
https://github.com/marketplace/actions/robocop-with-annotations

**Comment by mnojek** [comment]
Nice idea!
Why not to ask MarketSquare admin to accept it?

**Comment by bhirsz** [comment]
I will probably do this in the future - now I'm trying to get it working (I'm quite close though)

**Comment by bhirsz** [comment]
@mnojek 
Example PR here: https://github.com/bhirsz/actions-robocop/pull/3/files
By default it only reads configuration from the directory, it does not support passing any cli command (everything should be included in pyproject.toml or .robocop file).

**Comment by bhirsz** [comment]
Since the addition of the SARIF results (in Robocop 2.4.0) there is no need to create our own separate Github Workflow for running the Robocop. You can run Robocop and upload results from sarif report to register code issues in the Github. 

More examples in our docs https://robocop.readthedocs.io/en/stable/ci.html
