### ISSUE TITLE
Updating docs: replace missing-doc-testcase by missing-doc-test-case 

### ISSUE THREAD

**Issue by UliSei** [MarketSquare/robotframework-robocop#420]
I made some tests with VSCode and the .robocop configuration file and wondered why the excluded rule had no effect on the linted coding. I tested with the example of .robocop file:
```
--exclude missing-doc-testcase
--exclude missing-doc-suite
```
(see https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md)

The solution is obvious when Robocop is started from CLI:
```
>>>robocop --exclude missing-doc-testcase test.robot
### DEPRECATION WARNING: The name of the rule 'missing-doc-testcase' is renamed to 'missing-doc-test-case' starting from Robocop 1.8.0. Update your configuration if you're using old name. ###
```
Would you check whether missing-doc-testcase can be replaced by missing-doc-test-case, please?
There are occurences on
https://robocop.readthedocs.io/en/latest/user_guide.html and
https://robocop.readthedocs.io/en/latest/including_rules.html#including-rules

And there might be further docs to be updated. There were some more rules renamed in 1.8.0.

**Comment by mnojek** [comment]
Hello @UliSei and thanks for the nice catch! 📄 🐛 
I already fixed those issues in the documentation inside PR #419 along with some other typos.
This will be added with the next release.
