### ISSUE TITLE
Automatically detect new Robot Framework version

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#436]
If there is new version of Robot Framework released, open new issue in Robocop with title "Check compatibility with Robot Framework X" (X = version) or similar. Link to release notes in content of issue. 

This will allow us to detect new version and prepare Robocop for them. 

It's up to discussion if we should detect official versions (such as 4.1.1) or release candidates (4.1.1rc1) so we have extra time before release go live.

**Comment by bhirsz** [comment]
Since this task doesn't require extensive knowledge about our codebase - it's just providing way of quering/callbacks when there is new version of Robot Framework and then optionally creating issue in our project - I will set 'good first issue' label.

RF release notes are located there: 
https://github.com/robotframework/robotframework/tree/master/doc/releasenotes

**Comment by MalikMlitat** [comment]
I would like to work on this issue

**Comment by bhirsz** [comment]
> I would like to work on this issue

Let Me know if you need any extra information. Testing could be tricky (since it depends on release of particular package, in this case robot Framework). But I could create demo Python package that could be released on demand with incremented version and then we could switch from demo to robotframework when everything is ready.

What I have in mind would be for example github action triggerred on schedule (ie daily) and checking package version and if its new, create the issue. If you have other ideas then of course you can try it instead

**Comment by MalikMlitat** [comment]
well I was thinking something like: dependabot
see demo: https://github.com/MalikMlitat/demo/blob/main/.github/dependabot.yml
dependabot.yml checks (daily) via pip the newest version of robotframework and creates automatically  a pull-request :)
https://github.com/MalikMlitat/demo/pulls
see also: https://github.com/MalikMlitat/demo/network/updates

what do you think? should I go for it?

**Comment by bhirsz** [comment]
That's good idea - didn't thought about using dependabot but it will be perfect (and with PR it will run our tests on new version so even better). 

We don't want to update our official dependencies (let them stay at robotframework>=3.2.2) but we should update dependencies used for testing. See there for our github action: https://github.com/MarketSquare/robotframework-robocop/blob/master/.github/workflows/unit-tests.yml

We're using matrix with previous major version (only 3.2.2 for now) and then most recent one. We would need to change the logic here and move packages to separate requirements file (in separate directories and only for robotframework for now so dependabot will not pick up anything extra). 
For example we could create `stable3` (for robotframework=3.2.2) and `recent` (with recent robotframework version) directories, both with `requirements.txt` file. Then in https://github.com/MarketSquare/robotframework-robocop/blob/master/.github/workflows/unit-tests.yml :

```
(...)
        include:
          - os: 'ubuntu-latest'
            python-version: 3.6
            rf-version: 'stable3'
          - os: 'windows-latest'
            python-version: 3.9
            rf-version: 'recent'
          - os: 'ubuntu-latest'
            python-version: 3.7
            rf-version: 'recent'
(...)
      run: |
        python -m pip install --upgrade pip
        pip install -r {{ matrix.rf-version }}/requirements.txt
(...)
```

(and like always, it's proposal and I welcome better ideas)

**Comment by MalikMlitat** [comment]
@bhirsz thank you for the suggestion, since you have this matrix configuration, made it easy to adapt :
https://github.com/MalikMlitat/robotframework-robocop/commit/bcc060ec5fa3f2f6aa5c875a3abd72e6cb0aeb7e
but I could'nt verify that tests still running, dependabot works fine and detected the new version and created new PR

**Comment by bhirsz** [comment]
> @bhirsz thank you for the suggestion, since you have this matrix configuration, made it easy to adapt : [MalikMlitat@bcc060e](https://github.com/MalikMlitat/robotframework-robocop/commit/bcc060ec5fa3f2f6aa5c875a3abd72e6cb0aeb7e) but I could'nt verify that tests still running, dependabot works fine and detected the new version and created new PR

I saw PR - nicely done. There is typo (also in my example above with missing $) but it should be easy to fix. Unfortunately github action limits checks for first time contributors and we need to approve workflows for first PRs - later PRs will have automatically triggered builds.
