### ISSUE TITLE
[Bug] File containing "ň" is refused

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-robocop#455]
### What happened?

Robocop refuses to process the following file:
```
*** Keywords ***
Keyword
    [Documentation]  ň
    No Operation
```
complaining `Failed to decode <_io.TextIOWrapper name='C:\\git\\smart\\p\\p.robot' mode='r' encoding='cp1250'>. Default supported encoding by Robot Framework is UTF-8. Skipping file`. When the character 'ň' in `[Documentation]` is deleted, the file is processed normally. 

All my tools determined encoding of the file to be UTF-8, so the refusal of Robocop to process the file seems to be inappropriate.

Robot Framework can process such a file with no problem.

### Robocop version

1.9.0

**Comment by bhirsz** [comment]
Thank you for the report. It looks like it happens when we're reading the file to check for disablers (before running any check). I will fix it.

Some other letters for tests:
```
Ā ā Č č Ē ē Ģ ģ Ī ī Ķ ķ Ļ ļ Ņ ņ Š š Ū ū Ž ž
```

**Comment by MoreFamed** [comment]
Here is the complete list of Czech characters with accents, if you need something real to test on:
`ÁáÉéĚěÍíÓóÚúÝýŮůŘřŤťŠšĎďŽžČčŇň`. And Slovak ones are: `ĽľĹĺŔŕÄäô` 
:)
