### ISSUE TITLE
[Bug] Some characters considered invalid in embedded arguments

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-robocop#457]
### What happened?

There are still some issues regarding handling of embedded arguments. Some characters are denoted as invalid by W0301. The behaviour is very strange and depends on some things I consider insignificant. E.g. I have exactly this file:
```
*** Keywords ***
Perform A ${arg:\d+} ${arg2:\d+}
    Log To Console  ${arg}. ${arg2}

Perform ${arg:.*}
    Log To Console  ${arg}

```
Then in line 2, there both '$'s are denoted as invalid, and '{' in line 5 too. However, those keywords are written according to documentation and work perfectly when used in tests.

Besides, characters denoted as invalid depend on length of the keyword . E.g. when changing 'Perform A' to 'Perform ABCD', the first '+' is invalid instead of both '$'s. And when changing (the second) 'Perform' to 'Perform XY', '}' is considered invalid instead of '{'.

My configuration of the rule is `-c invalid-char-in-name:invalid_chars:!.?/;+'"()[]{}#$%^&=<>|\`

### Operating System

Windows

### Robocop version

1.10.0

**Comment by bhirsz** [comment]
`invalid_chars:!.?/;+'"()[]{}#$%^&=<>|\` I see you're not playing around :D 

I was not aware that regex could be used inside embedded variable - I used simpled matching system for this rule than the other that are is dealing with embedded vars. I will re-code it - thank you for test data as it will help me.
