### ISSUE TITLE
Let the rule 'invalid-char-in-name' define allowed characters

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-robocop#466]
When writing keywords in one particular project, one usually wants to use only one natural language for their names. (At least Indo-European) languages are written using just a few dozens characters each. One usually wants to allow keyword names to contain digits and several non-alphanumerical characters (space, underscore, hyphen....) as well -- and that's all. In other words, from thousands of possible characters, only several dozens are usually allowed to be used.

This is why I suggest adding one more option to the rule 'invalid-char-in-name'. Then a set of **allowed** characters would be listed in the rule. For brevity, I suggest implementing notation known from regexps where possible values of a character (given in brackets) could be given just as the first and the last item of a lists separated by hyphen. Example for Polish: :D one could probably have something like this line in their _.robocop_ file:   
`-c invalid-char-in-name:allowed_chars:A-Za-z0-9ĄąĆćĘęŁłŃńÓóŚśŹźŻż _-`

I have no idea how should be solved when defines both invalid and allowed chars for the rule. (Probably the same way how the situation is solved now when someone sets the same option of a rule twice with different values.)

**Comment by bhirsz** [comment]
It can be certainly implemented. If both invalid and allowed chars are defined then only allowed chars would be used. We could use both but it would create confusion and invalid chars are not needed when using allowed.
Configuring space would be problematic from cli but one could use \s or octal value of space.

**Comment by mnojek** [comment]
@MoreFamed I still can't find the scenario when it would be useful. Can you give us some possible cases that you think of? In my opinion, invalid characters is enough, no need to have both invalid and allowed, because they will be used interchangeably.

**Comment by MoreFamed** [comment]
Sorry for the delay. I want keyword names in our files to contain only these characters:
`a-zA-Z0-9ÁáÉéĚěÍíÓóÚúÝýŮůŘřŤťŠšĎďŽžČčŇň _-`, so I'd like to have some way in Robocop to check this.
@mnojek, how could I configure the current rule _invalid-char-in-name_ to do this using list of **invalid** chars? (Even if we consider just chars that can be typed on Czech keyboard in a direct way, there is no less than 150 of them.)

**Comment by mnojek** [comment]
I see now. That can be achieved. We need to decide if these parameters for the rule should be mutually excluded or not because we don't have such feature now. We'll get to you after we discuss it.
