### ISSUE TITLE
Add optional extented information to issues

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#468]
Some issues would benefit from extra longer description (with examples / links). It would be not displayed by default (but we could think about using --verbose option for that) but it could be passed to diagnostic json - so the extra information would be displayed in LSP plugin. 

https://microsoft.github.io/language-server-protocol/specification#diagnostic
Diagnostic for example allows to use codeDescription which have uri for extra information available. We could point to our docs where we could have extended documentation on rule.

**Comment by bhirsz** [comment]
Depends on #353

**Comment by mnojek** [comment]
Great idea!
