### ISSUE TITLE
[Bug] Rule 'not-allowed-char-in-name' handles non-ASCII chars (?) badly

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-robocop#492]
### What happened?

When I have line 
`-c not-allowed-char-in-name:pattern:[Á]`,
in my config file, Robocop crashes with trackback ending with
```
File "C:\Users\cen89549\AppData\Local\Programs\Python\Python37\lib\encodings\cp1250.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 147: character maps to <undefined>
```
It looks like Robocop treats the config file as if it were in CP1250 encoding; however, _file_ utility says it is in UTF-8. This might be source of the error.

### Operating System

Windows

### Robocop version

1.11.0

**Comment by bhirsz** [comment]
Thank you for the report - I can reproduce the bug. And I fixed it locally by using the same solution we did for fixing encoding issues with disablers (use external method for loading the file content which is encoding-secure).

**Comment by mnojek** [comment]
@MoreFamed New version of Robocop 1.11.2 was released that includes the fix for this. You can grab it by running `pip install -U robotframework-robocop` 😃
