### ISSUE TITLE
[Rule] Detect old for loop style

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#499]
Detect old for loop and suggest replacing it with new syntax:
```
  FOR  ${var}  IN  @{vars}
    \  Keyword
    \  ${std_out}  ${std_err}  Other Keyword
```
Both for `FOR` and `:FOR` style header. It's actually detected partially by RF parsing api as loop and then above example have following issues:
```
[E] 0412 Invalid for loop syntax: FOR loop has no closing END (invalid-for-loop)
[E] 1008 Indent expected (bad-indent)
[E] 1008 Indent expected (bad-indent)
```
Header with :FOR is not recognized at all. But it should have also (or instead) any information that this kind of syntax is deprecated.

**Comment by mnojek** [comment]
I don't think we need this rule, since it will be checking very old syntax, and I wonder how many users still use such an old RF release. @bhirsz What do you think? Should we close this one?

**Comment by bhirsz** [comment]
I assure it, they still use it because I was it even last week in the wild :) but checking for this isse is more problematic that it is worth it. I am also for closing it
