### ISSUE TITLE
Add names of problematic keywords/testcases/variables/sections to reports

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-robocop#500]
I suggest adding names of problematic keywords/testcases/variables/sections to Robocop's messages. There are many rules whose messages could undergo refinement; here are a few examples with my changes in bold:

0509 Section **ABC** is empty (empty-section)
0201 Missing documentation in keyword **ABC** (missing-doc-keyword)
0302 Keyword name **ABC** should use title case (wrong-case-in-keyword-name)
1009 Too many empty lines after section header **ABC** (1/0) (empty-line-after-section)
0305 Underscores in keyword name **ABC** can be replaced with spaces (underscore-in-keyword-name)
0307 Section name should be in format *** **Abc** *** or *** **ABC** *** (section-name-invalid)
0512 Documentation **of ABC** is empty (empty-documentation)

Motivation: when reading the report, one could imagine the problem better and more quickly without a link to source code (e.g. whether there is one bad char in the name, or a lot of them). Even when checking the problem in the source code, one can more easily spot the errorneous place with their eyes.  (There are number of lines written in messages; however, numbers are good for a computer, but names are good for a human. :))

**Comment by mnojek** [comment]
100% agree. We can work on it and it will benefit the users. Thanks for this suggestion!
