### ISSUE TITLE
Check settings name

### ISSUE THREAD

**Issue by mnojek** [MarketSquare/robotframework-robocop#509]
From RF User Guide:
"
Settings used to be also space-insensitive, but that was deprecated in Robot Framework 3.1 and trying to use something like `[T a g s]` causes an error in Robot Framework 3.2. Possible spaces between brackets and the name (e.g. `[ Tags ]`) are still allowed.
"

**Comment by bhirsz** [comment]
There is `setting-name-not-in-title-case` rule. It will detect `[arguments]` but not `[ Arguments ]`. Should we create another rule for extra checks or rather rework `setting-name-not-in-title-case` (together with rule name change, ie `invalid-setting-name`)? @mnojek

**Comment by bhirsz** [comment]
For reference there is `section-name-invalid` which checks case, spacing and formatting (`*** Name ***`)

**Comment by mnojek** [comment]
I think we can close this issue, because having spaces between the brackets is allowed, and I think there is no need to report it. We can add a rule that will enforce `[ Tags ]` or `[Tags]` based on the configuration, but I would say such rule would not be very useful (or would be?).

Lowercased setting like `[documentation]` are reported by `[W] 0306 Setting name '[documentation]' should use title or upper case (setting-name-not-in-title-case)`, and settings with spaces between characters like `[t e a r d o w n]` are also detected - `[E] 0408 Non-existing setting 't e a r d o w n'. Did you mean: Teardown (non-existing-setting)`.

So I think there is nothing more to add here. @bhirsz Let me know if I'm missing something.
