### ISSUE TITLE
[Bug] inconsistent default empty spaces between section for robocop and robotidy

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-robocop#536]
### What happened?

Robocop expects 2 empty lines between sections but robotidy formats it to 1 empty line. 
It might be good to compare other defaults as well. 
And maybe to add some test like this:

for each robocop rule which has corresponding robotidy formatter:
   add source file which breaks that rule
   assert robocop detects broken rule
   run robotidy
   assert robocop doesn't detect broken rule

### Robocop version

1.11.2

**Comment by bhirsz** [comment]
Yeah I agree we should align both tools. Inconsistent default empty spaces between sections is most obvious difference but I will check if there are other problems. 

There is also https://github.com/MarketSquare/robotframework-tidy/issues/186 which is somehow connected - I would need to implement special feature to tag robocop issues somehow so it would be possible to trigger robotidy to only fix given issue.

People have different opinions what should be default (ie 1 vs 2 empty lines) so most likely I will create polls in community for some of the choices.

**Comment by martinichka** [comment]
Hi @bhirsz, any idea on when this will be fixed?

And what would be a proper workaround for the time being?

Ignoring the error in RoboCop would be one:
`robocop test.robot -e 1003`

Or can I modify the behavior of RoboTidy with a config or even a patch?

**Comment by bhirsz** [comment]
To be honest I put this topic aside because it requires me to ask the community what they prefer (since what tidy does/robocop warns by default should be majority vote). But soon we're going to do major release of both tools - right after RF 5.0 release - so it maybe be the best time to ask. I will ask in Robot Framework slack.

**Comment by bhirsz** [comment]
And I see you now know how to configure the Robotidy. You can also use configuration files (https://robotidy.readthedocs.io/en/latest/configuration/config_file.html). It's bit offtopic but may come in handy.

**Comment by martinichka** [comment]
Cool, thank you for the update. Nice to know an update is coming with RF 5. For now the workaround is fine for us. Looking forward for the major release.

Thanks for the great work you did / are doing.

**Comment by bhirsz** [comment]
I've created the poll and (by veery slight difference) two empty lines won.  Robocop is already checking for that so I've updated Robotidy from 1 to 2 empty lines between sections as a default (in 2.1 release). Closing the issue.
