### ISSUE TITLE
Add one line IF support

### ISSUE THREAD

**Issue by mnojek** [MarketSquare/robotframework-robocop#546]
Robot Framework 5.0 will introduce one-liner for IF statements:

```
IF  ${val}==5  Keyword
```

Reference: robotframework/robotframework#4093

We need to support this new syntax and add new or update current rule.

**Comment by bhirsz** [comment]
Also possible INFO rule: for short IFs (ie without ELSE, ELSE IF, one statement, line under 120) recommend using infline IFs.

**Comment by bhirsz** [comment]
Related #578
