### ISSUE TITLE
Support new `RETURN` statement from RF 5.0

### ISSUE THREAD

**Issue by mnojek** [MarketSquare/robotframework-robocop#547]
Robot Framework 5.0 introduces new syntax for RETURN statement and we need to support it with new rules and also check if we need to deprecate or remove old ones.

Reference: robotframework/robotframework#4078

**Comment by bhirsz** [comment]
Possible rules (update old or add new):

1. Do not use `RETURN` as keyword name (reseved name)
2. Do not use `RETURN` in test case
3. Recommend using `RETURN` instead of `Return From Keyword`, `Return From Keyword If`, `Run Keyword And Return` and `Run Keyword And Return If`.

**Comment by bhirsz** [comment]
I see that 3. is highly related to #565 - once it's merged we can add extra check for following keywords/statements.

**Comment by bhirsz** [comment]
I will do 1. and 2. now. And I will check if we need to update previous rules (ie. keyword after `Return From Keyword`)

**Comment by bhirsz** [comment]
Partly covered by #570

**Comment by bhirsz** [comment]
Looks like all the cases are covered and PR merged - closing the issue.
