### ISSUE TITLE
[Bug] Rule 0302 is not Title Case

### ISSUE THREAD

**Issue by KUGA2** [MarketSquare/robotframework-robocop#548]
### What happened?

Rule 0302 says, its title case:
![image](https://user-images.githubusercontent.com/10581931/142586628-9643c56f-4395-402c-ac73-ad29fd7d9e4a.png)

According to title case definition ([wikipedia ](https://en.wikipedia.org/wiki/Title_case )and others) its not.

Capitalizing each word != Title Case
Depending on what type of Title Case is used, some words must be lowercase.

-> The rule for real title case would be quite some implementation. Also, you can also change the rule to `first_word_capitalized`, so the warning should read:
wrong-case-in-keyword-name: Keyword name does not adhere to "each_word_capitalized/first_word_capitalized"

PS: The same is probably true for other 03xx rules.

### Operating System

Documentation (=everywhere)

### Robocop version

stable

**Comment by bhirsz** [comment]
Hi, thanks for raising the issue (and sorry for the late reply). I agree that rule warning does not  adhere to title case definition. It should probably read "Keyword name does not follow case convention". I will look into it.

**Comment by mnojek** [comment]
I think that the only problem is with the rule's message which says it's title case while we check each word to be capitalized. So I updated the message to what @bhirsz proposed: `"Keyword name '{{ keyword_name }}' does not follow case convention"`.
IMO Everything else is fine.

**Comment by mnojek** [comment]
Thanks @KUGA2 for the report. I updated the message for the rule. The fix should be released along with the Robocop v.2.1.0 soon.
