### ISSUE TITLE
Add rules for BREAK, CONTINUE

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#557]
Handle BREAK and CONTINUE. Possible rules (update old or create new):

1. Do not name keyword after reserved words (#570)
2. Do not use BREAK, CONTINUE outside FOR, WHILE or TRY EXCEPT (check how it works - possibly prohibit in finally) (#562)
3. Recommend to use them inside IF statement (otherwise the code after them will be dead)
4. Label `Exit For Loop`, `Exit For Loop If`, `Continue For Loop`, `Continue For Loop If` as deprecated and suggest using BREAK or CONTINUE. (#576)

**Comment by mnojek** [comment]
Closing, because the point 3. was moved to #810.
