### ISSUE TITLE
Run Keyword Unless is deprecated

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#560]
https://github.com/robotframework/robotframework/issues/4174

**Comment by MalikMlitat** [comment]
I could take this issue to learn how to extend/create a rule

**Comment by bhirsz** [comment]
Unless it could be good idea to add extra rule (ie "deprecated-keyword") that would be Warning by default and it would catch Run Keyword Unless on top of if-can-be-used. Thanks for that we could enable "deprecated-keyword" only for given version of Robot Framework (">=5.0" in our case) and set "if-can-be-used" version to "4.*" (enable only for 4.* so for 5.0 it would be disabled). 

It would allow for backward compatiblity - before 5.0 `Run Keyword If` and `Run Keyword Unless` will throw if-can-be-used and after 5.0 deprecated-keyword. @mnojek what do you think?

**Comment by MalikMlitat** [comment]
Nice, thank you for the good explanation, I'll start with it in the next days

**Comment by bhirsz** [comment]
You can create new class - call it DeprecatedStatementChecker (bit more broad name because we will update this checker in the future when RF deprecate other statements and keywords)
