### ISSUE TITLE
TRY EXCEPT FINALLY from 5.0

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#569]
Robot Framework 5.0 introduce new syntax: TRY EXCEPT blocks. We need to handle them.

Things to consider:

1. ~~Other rules should be able to access TRY, EXCEPT, FINALLY, ELSE blocks.~~ (#574)
2. ~~Warn when trying to use this syntax as keyword name (Try, Except, finally..)~~ (#570).
3. Special rules? 
4. ~~Parsing errors - multiple FINALLY, EXCEPT blocks, wrong order (EXCEPT -> TRY, TRY -> FINALLY -> EXCEPT)~~

**Comment by bhirsz** [comment]
I will take care of 2)

**Comment by bhirsz** [comment]
Regarding 1. I'm going over the rules and updating the test. Updated so far:
  - missing-space-after-comment

**Comment by mnojek** [comment]
@bhirsz Do we still need to do something here? I see that points 1, 2 and 4 are completed.
Regarding point 3 - do you have any ideas for new rules related to TRY EXCEPT FINALLY?
If yes, let's create a separate issue for that. If not, let's close this ticket.

**Comment by bhirsz** [comment]
Robot Framework itself should catch various issues like double Else branch etc. But we would need to test it and include it at least as a parsing error test. For now I don't have aby ideas for the rules - if we came up with something we can create issue and for now we can close this one.

**Comment by mnojek** [comment]
Ok, closing this one.
I will instead add an issue for reviewing all Robot Framework parsing errors, because there could appear some more we did not include, when we were adding them on our side last time.
