### ISSUE TITLE
[Bug]  Rule 0901 keyword-after-return rise issue for  [Teardown] 

### ISSUE THREAD

**Issue by IlfirinPL** [MarketSquare/robotframework-robocop#588]
### What happened?

For this keyword will rise issue "RETURN is not defined at the end of keyword", I would consider to exclude  [Teardown] from this evaluation since teardown is actually last executed  

Keyword A
    [Arguments]    ${A}
    RETURN    ${A}
    [Teardown]    Set Log Level    INFO

### Operating System

N/A

### Robocop version

2.0.1

**Comment by bhirsz** [comment]
I confirm it's a bug - it should ignore settings (or just ignore ``[Teardown]`` like in your example).
