### ISSUE TITLE
[Bug] Rule 0912 Incorrectly recommend to use ${EMPTY}  for List and Dictionaries

### ISSUE THREAD

**Issue by IlfirinPL** [MarketSquare/robotframework-robocop#592]
### What happened?

 Rule 0912 Incorrectly recommend to use of ${EMPTY}  for lists
 Rule 0912 Incorrectly recommend to use of ${EMPTY}  for dictionary

Code below show the problem with ${EMPTY} is not the same as blank for lists ->  [''] != []
It`s  not valid entry for dictionary filled with ${EMPTY} 

*** Variables ***
@{A}    ${EMPTY}
@{B}
&{C}
&{D}    ${EMPTY}     #invalid entry 
*** Test Cases ***
Test
    Log To Console    ${A}
    Log To Console    ${B}
    Should Be Equal    ${A}    ${B}

### Operating System

N/A

### Robocop version

2.0.1

**Comment by mnojek** [comment]
I updated the rule to propose "empty" variable for the corresponding variable type:
- `${EMPTY}` for scalar
- `@{EMPTY}` for list
- `&{EMPTY}` for dict

**Comment by mnojek** [comment]
BTW It will be most likely released with Robocop version 2.1.0
