### ISSUE TITLE
[Bug] Weird message of rule 0319

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-robocop#593]
### What happened?

Hi. On RF 4.1.3, the rule says "'Run Keyword Unless' is deprecated since Robot Framework version **4**.*". 

But on RF 5.0, it says "'Run Keyword Unless' is deprecated since Robot Framework version **5**.*" etc. Both cannot be true. :)

### Robocop version

2.0.1

**Comment by mnojek** [comment]
Thanks @MoreFamed for the report. The issue is fixed now and should be released with Robocop v2.1.0. The deprecation message should be now shown only for RF5.
