### ISSUE TITLE
[Bug] Problem with custom rules file under VS-Code.

### ISSUE THREAD

**Issue by phermann-DGL** [MarketSquare/robotframework-robocop#612]
### What happened?

My Project Structure looks like this:
|-- .git
|-- src
 └ Robot-1
 └ Robot-2
  --  └ tests
   -- --     └ test.robot
 └ ...
|-- .robocop
|-- robocop-rules.py

My .robocop file looks like this:
`--reports all
--ext-rules robocop_rules.py
--exclude wrong-case-in-keyword-name
--configure too-many-calls-in-test-case:max_calls:30
--configure too-many-calls-in-keyword:max_calls:30
--configure too-long-test-case:max_len:50
--configure too-many-arguments:max_args:10
--configure line-too-long:line_length:200
--configure too-long-keyword:max_len:80
--configure file-too-long:max_lines:1000`

Running this from cmd from the root folder, works fine.
If i open the robot in vs code and hoover over the *** Settings *** it shows me this error:
`Error collecting Robocop errors: Fatal error: Failed to load external rules from file "robocop_rules.py". Verify if the file exists robotframework`

What have i toto that this works in vs-code too?

### Operating System

Windows

### Robocop version

2.0.2

**Comment by phermann-DGL** [comment]
only in the .robocop file

`--reports all
--ext-rules robocop_rules.py
--exclude wrong-case-in-keyword-name
--configure too-many-calls-in-test-case:max_calls:30
--configure too-many-calls-in-keyword:max_calls:30
--configure too-long-test-case:max_len:50
--configure too-many-arguments:max_args:10
--configure line-too-long:line_length:200
--configure too-long-keyword:max_len:80
--configure file-too-long:max_lines:1000`

**Comment by bhirsz** [comment]
Linked PR. In the next release this issue will be resolve for ``pyproject.toml`` files (you can use relative paths there). In ``.robocop`` case you still need either to use absolute paths or migrate to toml format. Hovewer this will be documented in our docs.
