### ISSUE TITLE
Create at least one report that logs date and time of checking RF scripts

### ISSUE THREAD

**Issue by UliSei** [MarketSquare/robotframework-robocop#628]
When I run robocop with 
`-o myfolder/robocop.log`
saving the logs at the same place, I just need to refresh the log file.
But I want to be sure that the most recent robocop result is displayed.

Currently I run Robocop with all reports and I get a log like this:

![grafik](https://user-images.githubusercontent.com/89480399/177187234-0c65c627-5c06-4bb9-8a6e-da4ded984bc2.png)

Wouldn't it be good to have at least one report that logs date and time when robocop was ended?

Either as an own report or
as extension of existing reports, e.g.:

- Report generated on 2022-07-04 17:50 by Robocop version: 2.1.0, 
- Scan finished in 5.973s on 2022-07-04 17:50

**Comment by bhirsz** [comment]
Good idea! Not sure though if we should create new report or reuse existing one (since it isn't a lot to add). @rikerfi does report generation time sounds good for version report or it should be printed somewhere else?

**Comment by mnojek** [comment]
I think I would go with a separate report, since it's not obvious that version report will also report the datetime, but I don't have a strong opinion and would like to hear from others.

**Comment by UliSei** [comment]
Maybe the datetime info is more related to robocop.reports.TimeTakenReport?
You get the time that was needed for the scan and additionally the timestamp when the scan had ended.
So there is even implicit the info when the scan was started.

**Comment by UliSei** [comment]
A separate report has some advantages: 

- it can be switched on or off just when needed independently from existing reports
- there is a low risk of messing up with consumers of the log which expect the status quo of existing reports output.

**Comment by bhirsz** [comment]
Timezones and time conversions, here we go again.. ;) OK, I don't have strong feelings in the subject so we can create separate report and make it configurable like @rikerfi suggested.

**Comment by rikerfi** [comment]
Time, what a pain in computer science :smile:
I could draft a report proposal during the weekend. Probably, I need to study configuration options a bit.

**Comment by bhirsz** [comment]
Implemented with timestamp report in #637. It will be released today as part of 2.3.0 release.

**Comment by UliSei** [comment]
Great - I like it!
