### ISSUE TITLE
Add Github Action to enforce running pre-commit

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#652]
Since we added pre-commit config in #651 we also need to enforce using it. We need to create github action that will be run on every PR with black/isort tools that will fail the job if the tools modify anything.

**Comment by OrrinGradwell** [comment]
Hi, I found this and this is exactly what I am after although I am not sure how to do this...

Is this still in active development or is there a solution already?

**Comment by mnojek** [comment]
> Hi, I found this and this is exactly what I am after although I am not sure how to do this...
> 
> Is this still in active development or is there a solution already?

Hi @OrrinGradwell . What exactly do you need? This is an issue created for our needs to enforce pre-commits inside this specific repository. How this relates to your case?

**Comment by bhirsz** [comment]
If you want to run Robocop in precommit, then we need git hook to our repository (like this one https://github.com/MarketSquare/robotframework-tidy/blob/main/.pre-commit-hooks.yaml ). We can do it if it's what you need

**Comment by OrrinGradwell** [comment]
I forgot to mention that I use the 'pyproject.toml' as my config file

**Comment by mnojek** [comment]
@OrrinGradwell Does you pre-commit check relate to `Robocop` (this project) in any way or you want to know how to configure Python pre-commits in your project?

**Comment by OrrinGradwell** [comment]
I want to include robocop as part of our existing pre-commit.

The pre-commit we have in place works as is, my goal is to lets say there are as an example is 10 warnings when running robocop, I want the pre-commit to know this and prevent the commit

In other words,

- Develop some robot framework code.
- when running git commit, robocop should be executed and the result should be used to decide if this commit is allowed.

if I have lets say 10 warnings and my threshold is set to 0, then the commit is stopped/prevented

**Comment by bhirsz** [comment]
Sorry for the questions, at first we thought you probably wanted to run something else - now it's clear, thanks for detailed explanation :) Like I said, in order to configure precommit like you did with other tools such as flake we need to create hook configuration file. It's rather simple to do so I will take care of that soon. Then you will be able to configure it in your precommit hook file in your project and robocop will automatically start. To track it watch #752 (since current issues is about something else).

For thresholds you will need extra configuration (hosted in pyproject.toml file) but I see you're already aware of that. After I add hook file I will also add pointers for you how to run it (or help if needed).

**Comment by OrrinGradwell** [comment]
You sir, are a legend!

thank you, and no problem on the questions, I'm a QA by trade so know all about it :D

**Comment by jylind** [comment]
Hi,
When will `.pre-commit-hooks.yaml` file be added to official release?

It seems to be missing from 2.6.0 so cannot use version number in my `.pre-commit-config.yaml`, only hash pointing to current master works.

**Comment by bhirsz** [comment]
Thanks for reaching out - the precommit file was already added to the main branch but then I hit a bit of the break from the OS and unfortunately we didn't have the release. I will prepare a next release cut that should also include this file (2.7.0).
