### ISSUE TITLE
[Bug] Many rules not applied when keyword is in an argument

### ISSUE THREAD

**Issue by sekwahs** [MarketSquare/robotframework-robocop#691]
### What happened?

Many rules do not get applied when a keyword is an argument to another keyword.

For example, checking underscore-in-keyword-name gets missed in all of the following. This severely limits how much code actually gets checkers applied.

  get_commissioning_json  1  # Finds
  run keywords
  ...  some_keyword  arg1  arg2  # Misses
  ...  AND
  ...  get Commissioning Json  5  # Misses
  run keywords  some_keyword  AND  get Commissioning_Json  6  # Misses
  run keyword and ignore error
  ...  some_keyword  # Misses
  run keyword and ignore error  some_keyword  # Misses

### Robocop version

\>= 2.0.1

**Comment by bhirsz** [comment]
I've added support for such cases recently to the ``robotidy``. It could be good time to do this also for ``robocop``. We can reuse``parse_run_keywords`` from https://github.com/MarketSquare/robotframework-tidy/blob/main/robotidy/transformers/RenameKeywords.py .

**Comment by bhirsz** [comment]
Should apply to following:

- not-allowed-char-in-name
- wrong-case-in-keyword-name
- keyword-name-is-reserved-word
- underscore-in-keyword-name

**Comment by bhirsz** [comment]
One edge case: run keywords can accept variable as keyword name. It should be ignored by above rules.

**Comment by bhirsz** [comment]
@sekwahsIssue I implemented support for keywords inside run keywords in Robocop 2.5.0 yesterday - please check and provide the feedback if necessary :)
