### ISSUE TITLE
Add verbose output

### ISSUE THREAD

**Issue by mnojek** [MarketSquare/robotframework-robocop#72]
Add CLI option to turn on verbose output and also a method that write lines to output if verbose is enabled.

**Comment by bhirsz** [comment]
@mnojek what is proposed output? (what to print, for example: what files were loaded, whole configuration before run etc)

**Comment by mnojek** [comment]
Honestly, I do not know. I remember that I have some ideas when I was creating this issue, but now I cannot recall them 😝 Maybe you have some?

**Comment by bhirsz** [comment]
I will go through whole flow and see what we can print. For example "found issue but ignored due in line disabler", "loaded config with..", "starting analyzing x file.." etc
