### ISSUE TITLE
Could the `dateutil` dependency by dropped?

### ISSUE THREAD

**Issue by fabioz** [MarketSquare/robotframework-robocop#743]
From what I see it's only usage is to get the local timezone, but this is available from the datetime directly.

See: https://stackoverflow.com/a/52606421/110451

Or am I missing something here?

**Comment by bhirsz** [comment]
I see we're using tzlocal() local from dateutil which is improved class over tzinfo from standard datetime. I will ask @rikerfi , do you know why we're using dateutil extra dependency over datetime? Timezones and time conversion are always black magic for me :)

**Comment by rikerfi** [comment]
Hey, this is a good point. I'll study and get back to you.

**Comment by mnojek** [comment]
I removed `dateutil` in #782
