### ISSUE TITLE
[Bug] Documentation code examples are missing characters

### ISSUE THREAD

**Issue by haklir** [MarketSquare/robotframework-robocop#745]
### What happened?

Characters missing in documentation code examples. Looking at the source files for documentation, everything looks as it should, but the web docs are missing some stuff. Looks like it could be caused by Django templating or something?

See examples:
- https://robocop.readthedocs.io/en/2.5.0/external_rules.html#rule-parameters
  - expected: `msg="There is '{{ variable }}' in test case name"`
  - actual: `msg="There is '' in test case name"`
- https://robocop.readthedocs.io/en/2.5.0/external_rules.html#templated-rule-messages
  - expected: `msg="You can supply variables like {{ variable }} or {{ number }}. "`
  - actual: `msg="You can supply variables like  or . "`

There are possibly other places with the same problem, I just happened to notice these as I am in the process of migrating external rules to robocop 2.

### Robocop version

2.5.0

**Comment by bhirsz** [comment]
Good find! You're right, I'm autogenerating some pages using konia templates and templating engine probably thinks it's not defined template variable and replace it with empty string.
