### ISSUE TITLE
[Bug] Providing `--argumentfile` is unuseful when default `.robocop` file exist

### ISSUE THREAD

**Issue by bosodo** [MarketSquare/robotframework-robocop#751]
### What happened?

If default .robocop file exist, the another config file witch is set as  `--argumentfile` from command line, is ignored. So I can't execute robocop with other configurations if default .robocop file exist in main directory.

### Operating System

Linux

### Robocop version

2.5.0, 2.6.0

**Comment by bhirsz** [comment]
Overriding configuration file should be possible so it's definitely a bug - I will investigate. Thanks!

**Comment by bhirsz** [comment]
It looks like it's outcome of several changes in the configuration file handling - where we wanted user to be able to use default configuration file while overriding some options in the cli. Hovewer it backfired us in a way where now where there is default configuration file in the directory it will be always loaded and some options (like --include, --exclude) cannot be overrided but only extended.

I think it would be best to still allow user adding some options from cli, ie:

```
robocop --verbose
```
which should load default configutation file and add verbose flag. But if user specify argument file in the cli then we  should not attempt to  search for the default configuration file.

Also, it looks like only ".robocop" file and not "pyproject.toml" file can be loaded using "-A/--argumentfile" option. It would be good to be able to load toml files using cli as well (I will open separate issue for it).
