### ISSUE TITLE
[Bug] Variables resource file generate warning missing documentation in suite

### ISSUE THREAD

**Issue by 4nif** [MarketSquare/robotframework-robocop#762]
### What happened?

Hello

I have `.resource` file and contains only `*** Variables *** inside the file. Is it possible to add rule to exclude warning for this? I don't want to disable `0203` rule for all resource or test cases

### Operating System

Mac

### Robocop version

2.6.0

**Comment by mnojek** [comment]
Hey @4nif,

Thanks for your question and sorry for a long delay.
I think the answer is described here in our documentation: [Ignore rules from source code](https://robocop.readthedocs.io/en/stable/including_rules.html#ignore-rule-from-source-code).
Basically, you can just add `# robocop: disable=0203` at the beginning of the file or `# robocop: disable=missing-doc-suite` (these are equivalents to each other) and the rule should be disabled only for this particular file.

Please try it out and let me know if it works.

**Comment by mnojek** [comment]
@4nif Has your problem been resolved, or do you still need our support?
