### ISSUE TITLE
List only enabled rules

### ISSUE THREAD

**Issue by jylind** [MarketSquare/robotframework-robocop#764]
As rule list is quite long already and growing I'd like a way of listing only the rules I have enabled.

It is quite impossible to spot only the enabled rules from all the all rules.

**Comment by bhirsz** [comment]
I agree, I did run the ``robocop --list`` just now and the list is long and hard to read (we have 119 rules already!). It would be bit hard to implement this without recontructing a lot of the code but the simple way would be adding special "keyword" enabled/disabled that would make robocop list only enabled/disabled rules:

robocop --list enabled
robocop --list disabled

Of course it would be not possible to use both list filtering and enabled/disabled syntax:

```
robocop --list *doc*
or
robocop --list enabled
```
Hovewer it would be still possible to achieve this by doing the following:
```
robocop --include *doc* --list enabled
```

Sounds like good improvement idea - I will take care of it.
