### ISSUE TITLE
underscore-in-keyword-name to support underscore prefix

### ISSUE THREAD

**Issue by jylind** [MarketSquare/robotframework-robocop#766]
We follow the practice (like in python) where resource or test suite "private" keywords start with underscores.

It would be nice if the rule `underscore-in-keyword-name` could support this, maybe it could be parameterized.

Then there could be a new rule to check that "private" keywords are not called outside of the resource file.

**Comment by mnojek** [comment]
Hey @jylind,

This idea for the rule seems like very specific to your project and is not something that is followed by the community commonly. I would suggest creating your own custom rule that is able to detect "private" keywords.
You can see how to create custom rules [here](https://robocop.readthedocs.io/en/stable/external_rules.html) in our documentation. This is where the underscores are detected in the keyword names. Following [this piece of code](https://github.com/MarketSquare/robotframework-robocop/blob/master/robocop/checkers/naming.py#L468-L485), it should be possible to write the rule you described.

If you need any further assistance, please let me know.

**Comment by mnojek** [comment]
@jylind There is also a [built-in way to mark user keywords as private](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#private-user-keywords) in Robot Framework.
Basically, you can just add `robot:private` tag to the keyword. It's a new feature in RF 6.0.

**Comment by jylind** [comment]
Hi,
Thanks for the info.
Actually I'm aware of this and in our case we will most probably use most.

As Robot Framework is implemented with Python it does borrow lot of ideologies from Python, at least how I see it.
Underscore, as the first character, in a method names (variables) hints that it should not be called outside of the module(class) where it has been created in.
Like the leading underscore, the private tag is not preventing the use of  these "private" keywords from any where  in the code.

For the reader (or reviewer) of the code, this tag is not visible unless they check every keyword if it contains this tag. But if the name of the keyword, in fact, starts with an underscore it is a clear sign to check if it has been declared in the same file or called outside

Of course, it would be create help if Robocop could throw an error in case a "private" keyword is called where it shouldn't.

But as is, the tag is more like a runtime indicator and that check is a bit too late. It should be caught earlier, in review or by CI in merge request.

**Comment by mnojek** [comment]
@jylind I see, good points.
Such custom rule can be written. Unfortunately, I don't have time at the moment, but maybe you can do it with your colleagues. As mentioned before, it'd better to follow this [piece of code](https://github.com/MarketSquare/robotframework-robocop/blob/master/robocop/checkers/naming.py#L468-L485) and read our documentation on [writing custom rules](https://robocop.readthedocs.io/en/stable/external_rules.html).
Good luck!

I am closing the issue, because we're not going to create such rule as a part of the Robocop itself.

PS We have an idea to create a project that will include custom rules created by the community. Maybe one day we will do it and your rule may become a part of the project 😉

**Comment by jylind** [comment]
👍 That's all fine.

I have not looked at all how those rules are written but to me it looks that I just take what is done for `underscore-in-keyword-name` and then exclude underscore if it happens to be the first char. No big deal.
Maybe it just is that simple maybe not.

But the truth is that I would anyway need to create my own `underscore-in-keyword-name` and `wrong-case-in-keyword-name`, at least, because the way we want to handle embedded arguments and those need to be anyhow excluded from the rules checks.

Then I will need to do the similar thing for `RenameKeywords` transformer in Robotidy.
It'll be fun exercise. 😁

**Comment by mnojek** [comment]
Good luck!  If you can (and if it's allowed), share the rules, when they're ready. Maybe someone else will benefit from them.
And don't hesitate to ask about anything. I will do my best to help.
