### ISSUE TITLE
Rule for resource file documentation

### ISSUE THREAD

**Issue by jylind** [MarketSquare/robotframework-robocop#776]
In Robocop, there should be a rule for checking documentation for resource files.
Same as there is already for Test Suite documentation.

I think it would be important to relay the information about use of the that particular resource file to test developers for not misusing the file.

**Comment by mnojek** [comment]
Hey @jylind,
Thanks for the suggestion. I added new rule W0204 called `missing-doc-resource-file` which checks if resource file has documentation.
The rule will be published with the next 2.8.0 release.
