### ISSUE TITLE
Does robocop support report output as json or sarif format directly?

### ISSUE THREAD

**Issue by thanasornsawan-doppio** [MarketSquare/robotframework-robocop#779]
Hi 

I think I stuck with the problem how to export robocop result from Jenkins to show on github. I don't want to use GitHub action cicd because complex functions and Jenkins server also private, other people not allow to access Jenkins result log.I just want to sent robocop log back to show on GitHub.

Does robocop support report output as json or sarif format directly? or any suggestion? because on robocop documentation has example only ".log"

I saw that it has library help [convert json to sarif](https://pypi.org/project/joern2sarif/) and then we can use [codeql api upload a SARIF file to GitHub code scanning ](https://codeql.github.com/docs/codeql-cli/manual/github-upload-results/#description)

**Comment by bhirsz** [comment]
Robocop supports Sarif output directly - and it works quite nicely with Github. It is described in our documentation: https://robocop.readthedocs.io/en/stable/ci.html#continuous-integration-support . It's done using our reports feature - after Robocop finishes analysis it produces the ".sarif.json" file in cwd directory. You can configure it to use different output directory/file name, see here: https://robocop.readthedocs.io/en/stable/reports.html#robocop.reports.SarifReport

If you have additional questions or you think we should improve something in the documentation then please let us know :)

**Comment by bhirsz** [comment]
I see though there is bug in our ``--list-reports`` option, it should list more reports with descriptions, but it only shows one of them. I will check that. The report should work, it only affect help messages in the Robocop.

**Comment by thanasornsawan-doppio** [comment]
Sorry I just see on documentation that it can export as sarif format.Thank you for your help
