### ISSUE TITLE
Support request: Error: File "[tool.robocop]" does not exist.

### ISSUE THREAD

**Issue by levlist** [MarketSquare/robotframework-robocop#786]
Hi,

I tried to create my own custom configuration using pyproject.toml file, but I get the following issue:
`Error: File "[tool.robocop]" does not exist.`

My setup:
Ubuntu 20.04
Python 3.8.10
Robocop 2.8.1

```
python3 -m pip freeze |grep toml
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.5
```
the "which" command prints the absolute path of robocop.
The interesting part is I also use robotidy with toml file and it works fine.

Maybe something is wrong with my toml file, so I would attach it:

[pyproject.toml.txt](https://github.com/MarketSquare/robotframework-robocop/files/10863908/pyproject.toml.txt)

Thank you in advance!

**Comment by levlist** [comment]
Yesterday I forgot to mention, I added an extra .txt extension because Github did not allow me to upload the .toml file.

**Comment by bhirsz** [comment]
This error suggest that somehow the first line of the toml config file is used as source path. How do you load the configuration file? There is difference betweeen robotidy and robocop:

robotidy:

- toml: load it with --config or loads automatically if the directory contains pyproject.toml

robocop

 - argument file: load with --argumentfile or loads automatically if the directory contains .robocop
- toml: loads automatically if the directory contains pyproject.toml

Like you see, pyproject.toml can be only loaded automatically in Robocop. If you you want support for ``--config`` for toml files so it does work the same as in Robotidy, this can be feature request (it was on my mind anyway). 

If you load the configuration file automatically and still get the error - I will try to reproduce it locally.
