### ISSUE TITLE
.toml file handling with --argumentfile parameter

### ISSUE THREAD

**Issue by levlist** [MarketSquare/robotframework-robocop#787]
Hi,

It would be useful if Robocop would handle the same way the .toml files as Robotidy.
To specify a .toml file in any location and with any name, use the --argumentfile parameter, just as you can specify it in Robotidy with the --config parameter.

This feature request is related to #786 support request.

Thank you in advance!

**Comment by bhirsz** [comment]
``--argumentfile`` is used for argument files so I think it would be best to introduce new option, ie ``--config`` just to load toml files. It have benefit of using the same naming convention as Robotidy so people used to one tool will be able to easily do the same in Robocop and vice versa. And also we don't need to check what's the format of loaded configuration if we assume that ``--argumentfile`` can only be argument file and ``--config`` toml file.

**Comment by levlist** [comment]
You are right!
Thank you!
