### ISSUE TITLE
Documentation: Marking the release for new rules

### ISSUE THREAD

**Issue by levlist** [MarketSquare/robotframework-robocop#788]
Hi,

you deliver new rules from release to release (thanks for that), but there is no information in the documentation what are the rules that have been introduced in the given release.
Could you please somehow mark the given rule that came with which release?

For example in the rule documentation table:
After "Rule severity", "Rule id", and "Robot Framework version" as a fourth column.

And/or highlight it as a new section in the Release notes.

Thank you in advance!

**Comment by levlist** [comment]
It would be a nice feature because it can help (at least for me), what are the new rules since I last checked the documentation page,

**Comment by mnojek** [comment]
Hey @levlist,
I was thinking about something like this some time ago. I will think if it's easy to achieve.

On the other side, you have a small dropdown menu with version selection and you should have all the rules listed for this specific version (if the rule was not implemented for the specific release, it will not be visible on the list).

https://user-images.githubusercontent.com/7412964/222407147-95062d04-25cc-4649-ba85-4aa668132361.mov

**Comment by bhirsz** [comment]
It should be easy to add as a feature - but of course it would then require a lot of manual work to check when given version was added.

From anyone implementing this (it could be me, just noting my thougs): Our rules page is autogenerated based on the rules defined in the Robocop. 

First we're autodiscovering the rules and created dictionary that will be passed to the rules.rst in the https://github.com/MarketSquare/robotframework-robocop/blob/master/docs/conf.py (see checker_docs[module_name] list creation). Then the rules.rst page is generated in the https://github.com/MarketSquare/robotframework-robocop/blob/master/docs/rules.rst . You can use previously supplied data, for example by adding another column in the table (after desc). 
And to actually retain the version info we could use Rule class from the https://github.com/MarketSquare/robotframework-robocop/blob/master/robocop/rules.py - by adding additional parameter, for example "version_added". It would be optional parameter (so the custom rules don't need to define it) but we could also add precommit that would be checking if all rules define the version they were added.

**Comment by levlist** [comment]
Thank you for your effort so far.
I hope you will have time for this in the near future. :-)

**Comment by mnojek** [comment]
Thanks @levlist! Of course, you are welcome to help us! Or you can at least spread the word to your colleagues. Maybe there is someone who wants to contribute to open-source 😉 We offer assistance and some fun! And I can guarantee +5 points to experience and programming skills in return 💪🏻 . And, of course, an eternal glory 🏆

**Comment by bhirsz** [comment]
@mnojek Are you working on it? Since this task is split to two: 1. adding version_added parameter and passing it to doc to display it) 2. Manually adding versions to rules, the work can be also split (ie I can take care of 1) or 2)).

**Comment by mnojek** [comment]
> @mnojek Are you working on it? Since this task is split to two: 1. adding version_added parameter and passing it to doc to display it) 2. Manually adding versions to rules, the work can be also split (ie I can take care of 1) or 2)).

I think we can add it, it will take time, but we can do it in small portions. 
If you want, you can add a PR with this new parameter and one example, and then we can split the work by the rule groups.

**Comment by bhirsz** [comment]
I've finished all changes in linked PR and it will be part of the next release - all Robocop rules will have information about the Robocop version when the rule was added.

![image](https://github.com/MarketSquare/robotframework-robocop/assets/8532066/fabd91ba-cf60-4485-9a6a-b3963fb28302)
