### ISSUE TITLE
Compatibility issue with "packaging" >= v23

### ISSUE THREAD

**Issue by axiom41** [MarketSquare/robotframework-robocop#792]
### What happened?

Hello.
During installation of the widely-used rpaframework package, a compatibility issue is raised between Robocop and "packaging" >= v23 (Robocop is stated compatible for v21 <= "packaging" < v23 while v23 is installed by rpaframework)
Would it be possible to release a Robocop version that is compatible also with "packaging" >= v23 or at least provide a workaround?
Thanks for your support.

### Operating System

Windows

### Robocop version

2.8.1

**Comment by mnojek** [comment]
It's fixed and will be released as a part of Robocop 2.9.0.
