### ISSUE TITLE
[Bug]  --list-reports does not list most of the reports

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#833]
```
robocop --list-reports
```
returns
```
Available reports:
return_status        - Checks if number of specific issues exceed quality gate limits
all                  - Turns on all default reports
```

**Comment by bhirsz** [comment]
It may be 'feature not a bug' situation. ``--list-reports`` was updated to only list enabled reports. Default reports are ``return_status`` and ``all``. If you configure other reports, they will show up:

```
> robocop --reports all --list-reports
Available reports:
file_stats           - Prints overall statistics about number of processed files
return_status        - Checks if number of specific issues exceed quality gate limits

```

It is useful to know which reports are currently enabled, but it is confusing to users that ``--list-reports`` only list enabled ones. It should list them all and perhaps add enabled/disabled tag next to it.

**Comment by bhirsz** [comment]
Implemented above suggestion in https://github.com/MarketSquare/robotframework-robocop/compare/list_reports_configured?expand=1, it will need tests & docs

**Comment by mnojek** [comment]
I think that `--list-reports` should always list all available reports, not enabled ones. We have 9 of them currently. Would be good to support `ENABLED` for `-lr` option, to only then see the enabled reports.

**Comment by mnojek** [comment]
And `all` should not be listed as a report, since it's a workaround to turn them all at once.

**Comment by bhirsz** [comment]
I agree. I will add support for ``ENABLED`` and I will move ``all`` to separate sentence, separate from the list of reports.

**Comment by bhirsz** [comment]
Also internal reports should not be printed - in this case ``return_status`` is our internal report which is always enabled. Same goes for ``json_report``. Also included this in linked PR
