### ISSUE TITLE
Split model from controller in config

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#837]
Our config class have all possible methods for both parsing and holding the config. We should at least split the controlling logic from model data to make it easier for future refactors.

**Comment by bhirsz** [comment]
I implemented this locally and managed to split the logic. Hovewer it works like a domino where refactoring one class leads to need to completely rewrite the other, then all the tests.. at this point I have realized we don't stand for any benefit of doing it (except for clearer code). We don't solve any problem but we possibly add more (hidden bugs with new implementation). I'm closing the issue for now, and we will need splitting model from controller in config for other issue in the future I will reuse the code I've created.

**Comment by mnojek** [comment]
Sure, glad that you've tried! And I agree that it's a risk to do such big refactor just for the sake of the clearer code, and with a high chance of introducing new bugs. Let's back to it when the need will be stronger.
