### ISSUE TITLE
[Bug] Fail pipeline if issues found 

### ISSUE THREAD

**Issue by MummanaSubramanya** [MarketSquare/robotframework-robocop#849]
### What happened?

I have configured my Tests on azure-pipeline  and when ever there is a commit it executes robocop and tests. Now here what I observed is, in robocop step even though there are some issues found, my pipeline is still green. Is there a way to mark it as fail if issues are found?

### What command/code did you try to run?

robocop --reports all --configure return_status:quality_gate:E=-1:W=-1:I=-1

### What is the full error message?

 No error. Details mentioned in description

### What did you expect to happen instead?

Pipeline should fail if issue is found

### Operating System

Windows

### Robocop version

3.1.1

**Comment by bhirsz** [comment]
If you setup quality gateway to -1 it ignores any issues for given severity when calculating return code. If you want to faul on any info/warning/error message then configure it to 0. More information here https://robocop.readthedocs.io/en/stable/user_guide.html#return-status

**Comment by mnojek** [comment]
@MummanaSubramanya Do you need some more help here or the issue is resolved based on the @bhirsz's comment?
