### ISSUE TITLE
Improve documentation formatting and structure

### ISSUE THREAD

**Issue by mnojek** [MarketSquare/robotframework-robocop#882]
I am not satisfied how the documentation looks like, especially the [Rules part](https://robocop.readthedocs.io/en/stable/rules.html):
- when scrolling, it's hard to see where one rule ends and another starts
- the rule `msg` and `docs` are one after another, sometimes mentioning the same thing twice
- the "New in Robocop" parameter may be moved outside the table I think

Above things can be improved and probably more, which I can't verbalize right now.
I will take a look and try to make the docs look more appealing and easier to understand.

**Comment by bhirsz** [comment]
Good idea, current design is already improvement over old one but there is still a lot to improve. 

The rule ``msg`` could be outlined so it's clear that is actually what rule produces (and it would explain why the message is similar to rule docs).
