### ISSUE TITLE
[Bug] Using --threshold E option hides an error

### ISSUE THREAD

**Issue by jyrlindr** [MarketSquare/robotframework-robocop#930]
### What happened?

Running robocop on a file containing one ERROR (file-too-long) gets hidden when using `--threshold E` argument.

Rule is configured as follows:
> --configure file-too-long:severity_threshold:warning=600:error=700

On the output list ERROR is the last one in the list.

When additional errors are created (listed before file-too-long) they are showing fine but still the file-too-long is missing.
F.g if there are 3 long line erros and file-too-long error, other are shown but not file-too-long error.

If `--threshold W` is used then in all cases all errors are shown.

### What command/code did you try to run?

poetry run robocop -t E -A config/robocop.cfg D:\dev\atc\resources\active_cables\ure.robot

### What is the full error message?

No error message.
Expected output is not produced.

### Operating System

Windows

### Robocop version

4.0.1

**Comment by bhirsz** [comment]
Thanks for the report, it seems it's connected to severity_threshold - it's not respected by threshold.
