### ISSUE TITLE
[Bug] ${_} should be ignored by duplicated-assigned-var-name

### ISSUE THREAD

**Issue by tnh8** [MarketSquare/robotframework-robocop#954]
### What happened?

While removing a bunch of `I0920 (unused-variable)` I used what the documentation says `Use ${_} variable name if you purposefully do not use variable` but in the following example:

```
    ${_}    ${_}    ${current}    ${_}=    Log get info
```
that results in `[W] 0812 Assigned variable name '${_}' is already used (duplicated-assigned-var-name)`.

### What did you expect to happen instead?

Nothing. Proposal is that `${_}` be made an exception to `W0812`.

### Robocop version

4.1.0

**Comment by bhirsz** [comment]
I agree, it should be ignored by this rule. I will fix it.

**Comment by bhirsz** [comment]
Released in 4.2.0
